version: "2"

linters:
  default: none
  enable:
    - copyloopvar
    - depguard
    - durationcheck
    - errcheck
    - forcetypeassert
    - godot
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usetesting
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          deny:
            - pkg: "github.com/hashicorp/terraform-plugin-sdk/v2" # prefix
              desc: "Use Terraform Plugin Framework"

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/pavel-snyk/terraform-provider-snyk

output:
  formats:
    tab:
      path: stdout
      colors: false
